/// @file Version.h
/// @brief Deterministic library version generated from library.json.
/// @warning Do not edit this file manually; run scripts/generate_version.py.
#pragma once

#include <cstdint>

namespace AT21CS {

inline constexpr uint16_t VERSION_MAJOR = 2;
inline constexpr uint16_t VERSION_MINOR = 0;
inline constexpr uint16_t VERSION_PATCH = 0;
inline constexpr uint32_t VERSION_CODE = 20000;
inline constexpr const char* VERSION = "2.0.0-rc.1";

}  // namespace AT21CS
