#!/usr/bin/env python3
"""Generate the deterministic public version header from library.json."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


if "__file__" in globals():
    ROOT = Path(__file__).resolve().parents[1]
elif "Import" in globals():
    Import("env")  # type: ignore[name-defined]
    ROOT = Path(env.subst("$PROJECT_DIR")).resolve()  # type: ignore[name-defined]
else:
    raise RuntimeError("cannot locate the AT21CS project root")
MANIFEST = ROOT / "library.json"
HEADER = ROOT / "include" / "AT21CS" / "Version.h"
SEMVER = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
    r"(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)


def load_version() -> tuple[str, int, int, int]:
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    version = data.get("version")
    if not isinstance(version, str):
        raise ValueError("library.json version must be a string")
    match = SEMVER.fullmatch(version)
    if match is None:
        raise ValueError(f"library.json version is not SemVer: {version!r}")
    return version, int(match.group(1)), int(match.group(2)), int(match.group(3))


def render(version: str, major: int, minor: int, patch: int) -> str:
    version_code = major * 10000 + minor * 100 + patch
    return f'''/// @file Version.h
/// @brief Deterministic library version generated from library.json.
/// @warning Do not edit this file manually; run scripts/generate_version.py.
#pragma once

#include <cstdint>

namespace AT21CS {{

inline constexpr uint16_t VERSION_MAJOR = {major};
inline constexpr uint16_t VERSION_MINOR = {minor};
inline constexpr uint16_t VERSION_PATCH = {patch};
inline constexpr uint32_t VERSION_CODE = {version_code};
inline constexpr const char* VERSION = "{version}";

}}  // namespace AT21CS
'''


def expected_bytes() -> bytes:
    return render(*load_version()).encode("utf-8")


def generate(check: bool) -> int:
    expected = expected_bytes()
    if check:
        try:
            actual = HEADER.read_bytes()
        except FileNotFoundError:
            print(f"version header is missing: {HEADER}", file=sys.stderr)
            return 1
        if actual != expected:
            print(
                "Version.h is stale; run python scripts/generate_version.py",
                file=sys.stderr,
            )
            return 1
        print("Version.h is deterministic and current")
        return 0

    if HEADER.is_file() and HEADER.read_bytes() == expected:
        print("Version.h is already current")
        return 0
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_bytes(expected)
    print(f"Generated {HEADER.relative_to(ROOT)} from library.json")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify Version.h without modifying it",
    )
    args = parser.parse_args()
    try:
        return generate(args.check)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"version generation failed: {error}", file=sys.stderr)
        return 1


if "Import" in globals():
    # PlatformIO executes extra scripts through SCons rather than __main__.
    if generate(check=False) != 0:
        raise RuntimeError("Version.h generation failed")
elif __name__ == "__main__":
    raise SystemExit(main())
